"""标准化错误码枚举

定义所有可能的错误类型,用于 CLI 输出的错误标识。
"""

from enum import Enum


class ErrorCode(str, Enum):
    """标准化错误码

    使用 str 继承确保序列化时输出字符串而非数字。
    错误码命名规范: {模块}_{错误类型}
    """

    # 认证相关 (AUTH_*)
    AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_REFRESH_FAILED = "AUTH_REFRESH_FAILED"

    # API 相关 (API_*)
    API_NETWORK_ERROR = "API_NETWORK_ERROR"
    API_RATE_LIMIT = "API_RATE_LIMIT"
    API_SERVER_ERROR = "API_SERVER_ERROR"
    API_INVALID_RESPONSE = "API_INVALID_RESPONSE"

    # 文件系统相关 (FILE_*)
    FILE_PERMISSION_ERROR = "FILE_PERMISSION_ERROR"
    FILE_DISK_FULL = "FILE_DISK_FULL"
    FILE_INVALID_PATH = "FILE_INVALID_PATH"

    # 下载相关 (DOWNLOAD_*)
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    DOWNLOAD_TIMEOUT = "DOWNLOAD_TIMEOUT"
    DOWNLOAD_PERMISSION_DENIED = "DOWNLOAD_PERMISSION_DENIED"
    DOWNLOAD_DISK_FULL = "DOWNLOAD_DISK_FULL"
    DOWNLOAD_FILE_EXISTS = "DOWNLOAD_FILE_EXISTS"
    DOWNLOAD_NETWORK_ERROR = "DOWNLOAD_NETWORK_ERROR"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # 元数据相关 (METADATA_*)
    METADATA_FETCH_FAILED = "METADATA_FETCH_FAILED"

    # 参数相关 (INVALID_*)
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"

    # 内部错误 (INTERNAL_*)
    INTERNAL_ERROR = "INTERNAL_ERROR"
